apiVersion: v1
kind: ConfigMap
metadata:
  name: namespace-watcher-config
  namespace: default
data:
  # Application settings
  REFERENCE_ENV: "test33"
  LOG_LEVEL: "INFO"
  IN_CLUSTER: "true"
  NAMESPACE_PREFIX: "test"
  NAMESPACE_LABEL_KEY: "createdBy"
  NAMESPACE_LABEL_VALUE: "koderover"
  
  # Feature flags
  ENABLE_CERT_MANAGEMENT: "true"
  ENABLE_DNS_MANAGEMENT: "true"
  ENABLE_AWS_RESOURCES: "true"
  ENABLE_KONG_ROUTES: "true"
  ENABLE_APOLLO_CONFIG: "true"
  ENABLE_ZADIG_WORKFLOW: "true"
  
  # Service URLs
  KONG_ADMIN_URL: "http://kong-kong-admin.proxy:8001"
  ZADIG_URL: "http://zadigx.shub.us"
  ZADIG_PROJECT_KEY: "fat-base-envrionment"
  ZADIG_GIT_REPO_OWNER: "your-git-org"
  ZADIG_GIT_REPO_NAME_TEMPLATE: "{namespace_name}"
  ZADIG_GIT_SERVICE_NAME_TEMPLATE: "{namespace_name}"
  ZADIG_GIT_TRIGGER_EVENTS: "push"
  ZADIG_DEFAULT_GIT_BRANCH: "main"
  
  # Database
  MYSQL_HOST: "192.168.0.50"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "ApolloConfigDB_fat"
  MYSQL_USER: "apollo_user"
  
  # cert-manager settings
  CERT_MANAGER_NAMESPACE: "cert-manager"
  CERT_MANAGER_ISSUER: "letsencrypt-dnsmadeeasy-prod"
  CERT_MANAGER_ISSUER_KIND: "ClusterIssuer"
  
  # AWS settings
  AWS_REGION: "ap-southeast-1"